# Generated by Django 3.2.7 on 2022-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('base', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms1', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms2', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms3', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms4', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms5', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms6', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms7', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms8', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms9', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms10', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms11', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms12', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms13', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms14', models.CharField(max_length=50, verbose_name='ベース')),
                ('symptoms15', models.CharField(max_length=50, verbose_name='ベース')),
            ],
            options={
                'verbose_name_plural': 'Tea',
            },
        ),
    ]
