# Generated by Django 3.2.7 on 2022-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='symptoms1',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms10',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms11',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms12',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms13',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms14',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms15',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms2',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms3',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms4',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms5',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms6',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms7',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms8',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='tea',
            name='symptoms9',
            field=models.CharField(max_length=50, verbose_name='症状'),
        ),
    ]
